import type { AppProps } from "next/app";
import Head from "next/head";

import { Roboto } from "@next/font/google";
import { globalStyles } from "../styles/global";
import { HeaderComponent } from "../components/HeaderComponent";
import { AppContainer } from "../styles/pages/app";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

globalStyles();

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className={roboto.className}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContainer>
        <HeaderComponent />
        <Component {...pageProps} />
      </AppContainer>
    </div>
  );
}
